spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: false
    contexts: dev

app:
  description: ${description}
  version: ${version}
  server:
    url: ${app.server.url}