spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db.changelog/changelog-master.xml
    enabled: true
    drop-first: true

app:
  server:
    url: ${app.server.url}